title: TOODO
email: yujo@student.42seoul.kr
description: >- # this means to ignore newlines until "baseurl:"
  TEST DESCRIPTION.
baseurl: ""
url: "https://yujo42.github.io/PROGRAM_42/docs"
github_username: YUJO42
remote_theme: h01000110/windows-95
plugins:
  - jekyll-feed

# for windows-95 theme
google_verification: null
sass:
  style: :compressed
  sass_dir: _sass
